config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #resources :restaurants

  get 'tasks/new', to: 'tasks#new', as: 'newtask'
  post 'tasks', to: 'tasks#create'

  get 'tasks', to: 'tasks#index'
  get 'tasks/:id', to: 'tasks#show', as: 'task'

  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edittask'
  patch 'tasks/:id', to: 'tasks#update', as: 'updatetask'

  delete 'tasks/:id', to: 'tasks#destroy', as: 'destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
    # @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(tasks_params)
    @task.save
    # redirect_to :controller => 'tasks', :action => 'index'
    redirect_to tasks_path
  end

  def edit
    # @task = Task.find(params[:id])
  end

  def update
    # @task = Task.find(params[:id])
    @task.update(tasks_params)
    redirect_to :controller => 'tasks', :action => 'index'
  end

  def destroy
    # @task = Task.find(params[:id])
    @task.destroy
    redirect_to :controller => 'tasks', :action => 'index'
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def tasks_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>EDIT TASK PAGE</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>This is my task index page</h1>

<ul>
  <% @tasks.each do |task| %>
  <% completed = task.completed ? "[X]" : "[ ]" %>
    <li><%= completed %> - <%= task.title%> - <%= link_to "Show details", task_path(task) %> - <%= link_to "Delete", destroy_path(task), method: :delete %></li>
  <% end %>
</ul>

<p><%= link_to "Add a new task", newtask_path %></p>

<!-- ICON ARROWS
<i class="fas fa-angle-double-right"></i>
 -->

app/views/tasks/new.html.erb
<h1> Create a new task: </h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1>TASK DETAILS PAGE</h1>

<h2><%= @task.title %></h2>

<p><%= @task.details %></p>

<% completed = @task.completed ? "Congrats 🥳 Task done" : "Still on your to-do list 🙄" %>

<p><%= completed %></p>

<p><%= link_to "Update task", edittask_path %></p>

<p><%= link_to "Back to task-list", tasks_path %></p>